# goreleaser config. See http://goreleaser.com for details.
before:
  hooks:
  - go mod download
builds:
- id: rbe_configs_gen
  env:
  main: ./cmd/rbe_configs_gen/rbe_configs_gen.go
  binary: rbe_configs_gen
  goos:
      - linux
      # Windows is untested.
      - windows
  goarch:
      - amd64
  # Set the binary timestamp to the commit timestamp it's being
  # built from.
  mod_timestamp: '{{ .CommitTimestamp }}'
archives:
-
  # Only upload binary assets.
  format: binary
  # Define how the prebuilt binaries uploaded as release assets are named.
  name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'