# Copyright 2021 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# goreleaser config. See http://goreleaser.com for details. Builds and releases the Bazel C++/Java
# remote execution toolchain generator as pre-built binaries.
before:
  # Make Go pre-download all dependencies before building any binaries to avoid clobbering parallel
  # builds.
  hooks:
  - go mod download
builds:
- id: rbe_configs_gen
  env:
  main: ./cmd/rbe_configs_gen/rbe_configs_gen.go
  binary: rbe_configs_gen
  goos:
      - linux
      # Windows is untested.
      - windows
  goarch:
      - amd64
  # Set the binary timestamp to the commit timestamp it's being
  # built from to make the produced binaries deterministic.
  mod_timestamp: '{{ .CommitTimestamp }}'
archives:
-
  # Only upload binary assets.
  format: binary
  # Define how the prebuilt binaries uploaded as release assets are named. The default includes the
  # version string in the binary name which is redundant because it is already included in the
  # release asset's URL.
  name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
