dist: trusty
sudo: required

os:
  - linux

python:
  - "2.7"

jdk:
  - oraclejdk8  # Building Bazel requires JDK8.

language: go
go: 1.10.x
install: true

services:
  - docker

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg'
    packages:
      - bazel

install:
  - go get -u github.com/bazelbuild/buildifier/buildifier

script:
  # Check that our direct testing passes.
  # The tests takes long to finish and currently we cover bazel tests in Bazel CI
  # TODO: add tests cannot be run by bazel here
  # - bazel clean && bazel test --test_output=errors //...

  # Check for issues with the format of our bazel config files.
  - buildifier -mode=check $(find . -name BUILD -type f)
  - buildifier -mode=check $(find . -name WORKSPACE -type f)
  - buildifier -mode=check $(find . -name '*.bzl' -type f)
