# Steps in this file use toolchain configs produced by rbe_default
# target with multiple versions of Bazel.
# Their purpose is to verify the checked in configs are usable on RBE
# with several older versions of Bazel

# Proper functioning of these test requires the _BAZEL_VERSION and
# _CONTAINER_MAJOR_VERSION substitution parameters to be set in the trigger
# with name "config: /bazel_tests_cloudbuild.yaml {_BAZEL_VERSION}"
# in https://pantheon.corp.google.com/cloud-build/triggers?project=asci-toolchain.
# _BAZEL_VERSION should point to a version of Bazel to verify with these tests
# _CONTAINER_MAJOR_VERSION must correspond to a valid container major version
# for which a toolchain config was published for the given bazel version.

steps:
# Test that runs with rbe_autoconfig with Bazel ${_BAZEL_VERSION}
# This test can only run with Bazel versions that have x.x.0 format
# as we only maintain bazelrc files for these.
- name: 'l.gcr.io/google/bazel:${_BAZEL_VERSION}'
  args:
  - --bazelrc=../../../../bazelrc/bazel-${_BAZEL_VERSION}.bazelrc
  - test
  - //:say_hello_test
  - --config=remote
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  dir: 'tests/rbe_repo/examples/bazel_toolchains_client'
