steps:
# Build the RBE Config generator using Go 1.15 for a few OS/arch combinations.
- name: golang:1.15
  env:
  - 'GOOS=linux'
  - 'GOARCH=amd64'
  args:
  - go
  - build
  - -o
  - rbe_configs_gen_linux_amd64
  - github.com/bazelbuild/bazel-toolchains/cmd/rbe_configs_gen
- name: golang:1.15
  env:
  - 'GOOS=windows'
  - 'GOARCH=amd64'
  args:
  - go
  - build
  - -o
  - rbe_configs_gen_windows_amd64.exe
  - github.com/bazelbuild/bazel-toolchains/cmd/rbe_configs_gen

# Upload all built Go binaries to our publicly readable GCS bucket. These binaries are uploaded
# for convenience only without any guarantees on their availability or functionality.
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'rbe_configs_gen_linux_amd64', 'gs://rbe-bazel-toolchains/cli-tools/latest/rbe_configs_gen_linux_amd64']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'rbe_configs_gen_windows_amd64.exe', 'gs://rbe-bazel-toolchains/cli-tools/latest/rbe_configs_gen_windows_amd64.exe']

