# Launch a RBE hello world build + unit test using the @rbe_default toolchain
# configs.
steps:
- name: 'marketplace.gcr.io/google/bazel'
  args:
  - --bazelrc=bazelrc/.bazelrc
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached
  waitFor: ["-"]

# Test that runs with Bazel 0.24.1 and uses checked-in configs directly
# w/o using rbe_autoconfig
- name: 'marketplace.gcr.io/google/bazel:0.24.1'
  args:
  - --bazelrc=bazelrc/.bazelrc.test
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --host_javabase=//configs/ubuntu16_04_clang/9.0.0/bazel_0.24.1/java:jdk
  - --javabase=//configs/ubuntu16_04_clang/9.0.0/bazel_0.24.1/java:jdk
  - --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --crosstool_top=//configs/ubuntu16_04_clang/9.0.0/bazel_0.24.1/cc:toolchain
  - --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
  - --extra_toolchains=//configs/ubuntu16_04_clang/9.0.0/bazel_0.24.1/config:cc-toolchain
  - --extra_execution_platforms=//configs/ubuntu16_04_clang/9.0.0/bazel_0.24.1/config:platform
  - --host_platform=//configs/ubuntu16_04_clang/9.0.0/bazel_0.24.1/config:platform
  - --platforms=//configs/ubuntu16_04_clang/9.0.0/bazel_0.24.1/config:platform
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached
  waitFor: ["-"]

# Test that runs with rbe_autoconfig with bazel0.24.1
- name: 'marketplace.gcr.io/google/bazel:0.24.1'
  args:
  - --bazelrc=bazelrc/.bazelrc
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached
  waitFor: ["-"]

# Test that runs with rbe_autoconfig with bazel0.24.0
- name: 'marketplace.gcr.io/google/bazel:0.24.0'
  args:
  - --bazelrc=bazelrc/.bazelrc
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached
  waitFor: ["-"]

# Test that runs with rbe_autoconfig with bazel0.23.2
- name: 'marketplace.gcr.io/google/bazel:0.23.2'
  args:
  - --bazelrc=bazelrc/.bazelrc
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached
  waitFor: ["-"]

# Test that runs with rbe_autoconfig with bazel0.23.1
- name: 'marketplace.gcr.io/google/bazel:0.23.1'
  args:
  - --bazelrc=bazelrc/.bazelrc
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached
  waitFor: ["-"]

# Test that runs with rbe_autoconfig with bazel0.23.0
- name: 'marketplace.gcr.io/google/bazel:0.23.0'
  args:
  - --bazelrc=bazelrc/.bazelrc
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached
  waitFor: ["-"]

# Test that runs with rbe_autoconfig with bazel0.22.0
- name: 'marketplace.gcr.io/google/bazel:0.22.0'
  args:
  - --bazelrc=bazelrc/.bazelrc
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached
  waitFor: ["-"]

# Test that runs with rbe_autoconfig with bazel0.21.0
- name: 'marketplace.gcr.io/google/bazel:0.21.0'
  args:
  - --bazelrc=bazelrc/.bazelrc
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached
  waitFor: ["-"]
