# Launch a RBE hello world build + unit test using the @rbe_default toolchain
# configs.
steps:
- name: 'marketplace.gcr.io/google/bazel'
  args:
  - --bazelrc=bazelrc/.bazelrc
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached

# Test that runs with rbe_autoconfig_autogen_ubuntu1604 with latest Bazel.
# This test exersises the target that is used to produce configs that
# are checked into this repo.
- name: 'gcr.io/asci-toolchain/nosla-ubuntu16_04-bazel-docker-gcloud'
  args:
  - /usr/local/bin/bazel
  - --bazelrc=bazelrc/.bazelrc.test
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --host_javabase=@rbe_autoconfig_autogen_ubuntu1604//java:jdk
  - --javabase=@rbe_autoconfig_autogen_ubuntu1604//java:jdk
  - --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --crosstool_top=@rbe_autoconfig_autogen_ubuntu1604//cc:toolchain
  - --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
  - --extra_toolchains=@rbe_autoconfig_autogen_ubuntu1604//config:cc-toolchain
  - --extra_execution_platforms=@rbe_autoconfig_autogen_ubuntu1604//config:platform
  - --host_platform=@rbe_autoconfig_autogen_ubuntu1604//config:platform
  - --platforms=@rbe_autoconfig_autogen_ubuntu1604//config:platform
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached
  env: ['RBE_AUTOCONF_ROOT=/workspace']
