steps:
# Launch a RBE hello world build + unit test using the @rbe_default toolchain
# configs.
- name: 'l.gcr.io/google/bazel'
  args:
  - --bazelrc=../../../../bazelrc/latest.bazelrc
  - test
  - //:say_hello_test
  - --config=remote
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  dir: 'tests/rbe_repo/examples/bazel_toolchains_client'

