steps:
# Launch a RBE hello world build + unit test using the @rbe_default toolchain
# configs.
- name: 'l.gcr.io/google/bazel'
  args:
  - --bazelrc=../../../../bazelrc/.bazelrc
  - test
  - //:say_hello_test
  - --config=remote
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  dir: 'tests/rbe_repo/examples/bazel_toolchains_client'

# Launch a RBE hello world build + unit test using the manually produced
# configs for Bazel 0.25.0
- name: 'l.gcr.io/google/bazel'
  args:
  - --bazelrc=../../../../bazelrc/bazel-0.25.0.bazelrc
  - test
  - //:say_hello_test
  - --config=remote
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached
  dir: 'tests/rbe_repo/examples/bazel_toolchains_client'
