# Launch a RBE hello world build + unit test using the @rbe_default toolchain
# configs.
steps:
- name: 'marketplace.gcr.io/google/bazel'
  args:
  - --bazelrc=bazelrc/.bazelrc
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --remote_instance_name=projects/bazel-untrusted/instances/default_instance
  - --noremote_accept_cached

# Specify a custom GCS bucket hosted on the GCP project owned by toolchains
# team to upload logs.
logsBucket: "gs://asci-toolchain-gcb-logs-bucket-from-bazel-untrusted"

