# Steps in this file use toolchain configs produced by rbe_autoconf**
# targets. Their purpose is to verify the configs are usable on RBE.
- name: 'marketplace.gcr.io/google/bazel'
  args:
  - --bazelrc=bazelrc/.bazelrc.test
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --host_javabase=@rbe_autoconf_checked_in//java:jdk
  - --javabase=@rbe_autoconf_checked_in//java:jdk
  - --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --crosstool_top=@rbe_autoconf_checked_in//cc:toolchain
  - --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
  - --extra_toolchains=@rbe_autoconf_checked_in//config:cc-toolchain
  - --extra_execution_platforms=@rbe_autoconf_checked_in//config:platform
  - --host_platform=@rbe_autoconf_checked_in//config:platform
  - --platforms=@rbe_autoconf_checked_in//config:platform
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached

- name: 'marketplace.gcr.io/google/bazel'
  args:
  - --bazelrc=bazelrc/.bazelrc.test
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --host_javabase=@rbe_autoconf_checked_in_no_java//java:jdk
  - --javabase=@rbe_autoconf_checked_in_no_java//java:jdk
  - --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --crosstool_top=@rbe_autoconf_checked_in_no_java//cc:toolchain
  - --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
  - --extra_toolchains=@rbe_autoconf_checked_in_no_java//config:cc-toolchain
  - --extra_execution_platforms=@rbe_autoconf_checked_in_no_java//config:platform
  - --host_platform=@rbe_autoconf_checked_in_no_java//config:platform
  - --platforms=@rbe_autoconf_checked_in_no_java//config:platform
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached

- name: 'gcr.io/asci-toolchain/nosla-ubuntu16_04-bazel-docker-gcloud'
  args:
  - /usr/local/bin/bazel
  - --bazelrc=bazelrc/.bazelrc.test
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --host_javabase=@rbe_autoconf_generate//java:jdk
  - --javabase=@rbe_autoconf_generate//java:jdk
  - --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --crosstool_top=@rbe_autoconf_generate//cc:toolchain
  - --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
  - --extra_toolchains=@rbe_autoconf_generate//config:cc-toolchain
  - --extra_execution_platforms=@rbe_autoconf_generate//config:platform
  - --host_platform=@rbe_autoconf_generate//config:platform
  - --platforms=@rbe_autoconf_generate//config:platform
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached

- name: 'gcr.io/asci-toolchain/nosla-ubuntu16_04-bazel-docker-gcloud'
  args:
  - /usr/local/bin/bazel
  - --bazelrc=bazelrc/.bazelrc.test
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --host_javabase=@rbe_autoconf_generate_no_java//java:jdk
  - --javabase=@rbe_autoconf_generate_no_java//java:jdk
  - --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --crosstool_top=@rbe_autoconf_generate_no_java//cc:toolchain
  - --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
  - --extra_toolchains=@rbe_autoconf_generate_no_java//config:cc-toolchain
  - --extra_execution_platforms=@rbe_autoconf_generate_no_java//config:platform
  - --host_platform=@rbe_autoconf_generate_no_java//config:platform
  - --platforms=@rbe_autoconf_generate_no_java//config:platform
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached

- name: 'gcr.io/asci-toolchain/nosla-ubuntu16_04-bazel-docker-gcloud'
  args:
  - /usr/local/bin/bazel
  - --bazelrc=bazelrc/.bazelrc.test
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --host_javabase=@rbe_autoconf_config_repos//java:jdk
  - --javabase=@rbe_autoconf_config_repos//java:jdk
  - --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --crosstool_top=@rbe_autoconf_config_repos//cc:toolchain
  - --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
  - --extra_toolchains=@rbe_autoconf_config_repos//config:cc-toolchain
  - --extra_execution_platforms=@rbe_autoconf_config_repos//config:platform
  - --host_platform=@rbe_autoconf_config_repos//config:platform
  - --platforms=@rbe_autoconf_config_repos//config:platform
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached

- name: 'marketplace.gcr.io/google/bazel'
  args:
  - --bazelrc=bazelrc/.bazelrc.test
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --host_javabase=@rbe_autoconf_old_container//java:jdk
  - --javabase=@rbe_autoconf_old_container//java:jdk
  - --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --crosstool_top=@rbe_autoconf_old_container//cc:toolchain
  - --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
  - --extra_toolchains=@rbe_autoconf_old_container//config:cc-toolchain
  - --extra_execution_platforms=@rbe_autoconf_old_container//config:platform
  - --host_platform=@rbe_autoconf_old_container//config:platform
  - --platforms=@rbe_autoconf_old_container//config:platform
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached

- name: 'marketplace.gcr.io/google/bazel'
  args:
  - --bazelrc=bazelrc/.bazelrc.test
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --host_javabase=@rbe_autoconf_base_container_digest//java:jdk
  - --javabase=@rbe_autoconf_base_container_digest//java:jdk
  - --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --crosstool_top=@rbe_autoconf_base_container_digest//cc:toolchain
  - --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
  - --extra_toolchains=@rbe_autoconf_base_container_digest//config:cc-toolchain
  - --extra_execution_platforms=@rbe_autoconf_base_container_digest//config:platform
  - --host_platform=@rbe_autoconf_base_container_digest//config:platform
  - --platforms=@rbe_autoconf_base_container_digest//config:platform
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached

- name: 'marketplace.gcr.io/google/bazel'
  args:
  - --bazelrc=bazelrc/.bazelrc.test
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --host_javabase=@rbe_autoconf_constraints//java:jdk
  - --javabase=@rbe_autoconf_constraints//java:jdk
  - --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --crosstool_top=@rbe_autoconf_constraints//cc:toolchain
  - --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
  - --extra_toolchains=@rbe_autoconf_constraints//config:cc-toolchain
  - --extra_execution_platforms=@rbe_autoconf_constraints//config:platform
  - --host_platform=@rbe_autoconf_constraints//config:platform
  - --platforms=@rbe_autoconf_constraints//config:platform
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached

- name: 'gcr.io/asci-toolchain/nosla-ubuntu16_04-bazel-docker-gcloud'
  args:
  - /usr/local/bin/bazel
  - --bazelrc=bazelrc/.bazelrc.test
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --host_javabase=@rbe_autoconf_resovle_tag//java:jdk
  - --javabase=@rbe_autoconf_resovle_tag//java:jdk
  - --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --crosstool_top=@rbe_autoconf_resovle_tag//cc:toolchain
  - --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
  - --extra_toolchains=@rbe_autoconf_resovle_tag//config:cc-toolchain
  - --extra_execution_platforms=@rbe_autoconf_resovle_tag//config:platform
  - --host_platform=@rbe_autoconf_resovle_tag//config:platform
  - --platforms=@rbe_autoconf_resovle_tag//config:platform
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached

- name: 'gcr.io/asci-toolchain/nosla-ubuntu16_04-bazel-docker-gcloud'
  args:
  - /usr/local/bin/bazel
  - --bazelrc=bazelrc/.bazelrc.test
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --host_javabase=@rbe_autoconf_output_base//java:jdk
  - --javabase=@rbe_autoconf_output_base//java:jdk
  - --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --crosstool_top=@rbe_autoconf_output_base//cc:toolchain
  - --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
  - --extra_toolchains=@rbe_autoconf_output_base//config:cc-toolchain
  - --extra_execution_platforms=@rbe_autoconf_output_base//config:platform
  - --host_platform=@rbe_autoconf_output_base//config:platform
  - --platforms=@rbe_autoconf_output_base//config:platform
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached
  env: ['RBE_AUTOCONF_ROOT=/workspace']

- name: 'gcr.io/asci-toolchain/nosla-ubuntu16_04-bazel-docker-gcloud'
  args:
  - /usr/local/bin/bazel
  - --bazelrc=bazelrc/.bazelrc.test
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --host_javabase=@rbe_autoconf_output_base_no_java//java:jdk
  - --javabase=@rbe_autoconf_output_base_no_java//java:jdk
  - --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --crosstool_top=@rbe_autoconf_output_base_no_java//cc:toolchain
  - --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
  - --extra_toolchains=@rbe_autoconf_output_base_no_java//config:cc-toolchain
  - --extra_execution_platforms=@rbe_autoconf_output_base_no_java//config:platform
  - --host_platform=@rbe_autoconf_output_base_no_java//config:platform
  - --platforms=@rbe_autoconf_output_base_no_java//config:platform
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached
  env: ['RBE_AUTOCONF_ROOT=/workspace']

- name: 'gcr.io/asci-toolchain/nosla-ubuntu16_04-bazel-docker-gcloud'
  args:
  - /usr/local/bin/bazel
  - --bazelrc=bazelrc/.bazelrc.test
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --host_javabase=@rbe_autoconf_config_repos_output_base//java:jdk
  - --javabase=@rbe_autoconf_config_repos_output_base//java:jdk
  - --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --crosstool_top=@rbe_autoconf_config_repos_output_base//cc:toolchain
  - --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
  - --extra_toolchains=@rbe_autoconf_config_repos_output_base//config:cc-toolchain
  - --extra_execution_platforms=@rbe_autoconf_config_repos_output_base//config:platform
  - --host_platform=@rbe_autoconf_config_repos_output_base//config:platform
  - --platforms=@rbe_autoconf_config_repos_output_base//config:platform
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached
  env: ['RBE_AUTOCONF_ROOT=/workspace']

- name: 'marketplace.gcr.io/google/bazel'
  args:
  - --bazelrc=bazelrc/.bazelrc.test
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --host_javabase=@rbe_autoconf_generate_no_docker_pull//java:jdk
  - --javabase=@rbe_autoconf_generate_no_docker_pull//java:jdk
  - --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --crosstool_top=@rbe_autoconf_generate_no_docker_pull//cc:toolchain
  - --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
  - --extra_toolchains=@rbe_autoconf_generate_no_docker_pull//config:cc-toolchain
  - --extra_execution_platforms=@rbe_autoconf_generate_no_docker_pull//config:platform
  - --host_platform=@rbe_autoconf_generate_no_docker_pull//config:platform
  - --platforms=@rbe_autoconf_generate_no_docker_pull//config:platform
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached

- name: 'gcr.io/asci-toolchain/nosla-ubuntu16_04-bazel-docker-gcloud'
  args:
  - /usr/local/bin/bazel
  - --bazelrc=bazelrc/.bazelrc.test
  - test
  - //examples/remotebuildexecution/hello_world/cc:say_hello_test
  - --config=remote
  - --host_javabase=@rbe_autoconf_custom_container//java:jdk
  - --javabase=@rbe_autoconf_custom_container//java:jdk
  - --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
  - --crosstool_top=@rbe_autoconf_custom_container//cc:toolchain
  - --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
  - --extra_toolchains=@rbe_autoconf_custom_container//config:cc-toolchain
  - --extra_execution_platforms=@rbe_autoconf_custom_container//config:platform
  - --host_platform=@rbe_autoconf_custom_container//config:platform
  - --platforms=@rbe_autoconf_custom_container//config:platform
  - --remote_instance_name=projects/asci-toolchain/instances/default_instance
  - --noremote_accept_cached
