load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["packages.go"],
    importpath = "github.com/bazelbuild/bazel-toolchains/src/go/pkg/metadata",
    visibility = ["//visibility:public"],
)
