# Copyright 2017 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name = "bazel_toolchains_client")

local_repository(
    name = "bazel_toolchains",
    path = "../../../..",
)

local_repository(
    name = "toolchain_config_host",
    path = "../toolchain_config_host",
)

load("@bazel_toolchains//rules:rbe_repo.bzl", "rbe_autoconfig")

rbe_autoconfig(
    name = "rbe_default",
    #TODO: reenable once 0.26.0 configs are out
    #use_checked_in_confs = "Force",
)

load(
    "@toolchain_config_host//configs/test_configs:repo.bzl",
    "CUSTOM_ENV1",
    "CUSTOM_ENV2",
    "CUSTOM_ENV3",
    "CUSTOM_RBE_REPO",
)

# Basic test for rbe_custom, the corresponding GCB build should first
# build the @toolchain_config_host so this one can use those.
rbe_autoconfig(
    name = "rbe_custom",
    rbe_repo = CUSTOM_RBE_REPO,
    use_checked_in_confs = "Force",
)

# Should use checked-in configs as, even though container is specified, latest is
# set as tag.
rbe_autoconfig(
    name = "rbe_custom_tag_latest",
    rbe_repo = CUSTOM_RBE_REPO,
    registry = CUSTOM_RBE_REPO["container_registry"],
    repository = CUSTOM_RBE_REPO["container_repo"],
    tag = "latest",
    use_checked_in_confs = "Force",
)

# This test should generate configs as we use a custom env.
rbe_autoconfig(
    name = "rbe_custom_generate_env",
    env = {"CUSTOM_KEY": "CUSTOM_VALUE"},
    rbe_repo = CUSTOM_RBE_REPO,
)

# This test uses the custom rbe_repo. It should not generate configs as, even
# though target overrides repository and digest (using rbe-ubuntu16-04
# container), its setting the base container digest to point to a compatible
# bazel one for which configs are pre-generated.
# TODO: point this to use values from ubuntu config file in bazel_toolchains repo
rbe_autoconfig(
    name = "rbe_custom_base_container_digest",
    base_container_digest = CUSTOM_RBE_REPO.get("config_versions").latest_container,
    digest = "sha256:94d7d8552902d228c32c8c148cc13f0effc2b4837757a6e95b73fdc5c5e4b07b",
    rbe_repo = CUSTOM_RBE_REPO,
    registry = "gcr.io",
    repository = "google/rbe-ubuntu16-04",
    use_checked_in_confs = "Force",
)

# This one should not generate configs either, as, even though it uses a custom
# config_name, the preeceding step which builds @rbe_custom_config_name in
# @toolchain_config_host should generate the configs.
rbe_autoconfig(
    name = "rbe_custom_config_name",
    config_name = "test_config_name",
    rbe_repo = CUSTOM_RBE_REPO,
    use_checked_in_confs = "Force",
)

# The three tests below should not generate configs as the corresponding
# targets in @toolchain_config_host should pre-generate them.
# These tests validate the versions.bzl file can be modified by
# several configs and remain valid.
rbe_autoconfig(
    name = "rbe_custom_env1",
    config_name = "test_env1",
    env = CUSTOM_ENV1,
    rbe_repo = CUSTOM_RBE_REPO,
    use_checked_in_confs = "Force",
)

rbe_autoconfig(
    name = "rbe_custom_env2",
    config_name = "test_env2",
    env = CUSTOM_ENV2,
    rbe_repo = CUSTOM_RBE_REPO,
    use_checked_in_confs = "Force",
)

rbe_autoconfig(
    name = "rbe_custom_env3",
    config_name = "test_env3",
    env = CUSTOM_ENV3,
    rbe_repo = CUSTOM_RBE_REPO,
    use_checked_in_confs = "Force",
)
